# Generated by Django 4.2.13 on 2024-05-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Identifier')),
                ('description', models.CharField(max_length=255, verbose_name='Todo description')),
                ('deadline', models.CharField(max_length=255, verbose_name='Deadline')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
