# Generated by Django 4.2.13 on 2024-05-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='identifier',
            field=models.CharField(default='aee687e5-ad4c-4643-bb52-00d41edb9c2f', max_length=255, unique=True, verbose_name='Identifier'),
        ),
    ]
