# Generated by Django 4.2.13 on 2024-05-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.CharField(max_length=255, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='identifier',
            field=models.CharField(max_length=255, verbose_name='Identifier'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
