# Generated by Django 4.2.13 on 2024-06-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='ww', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='78bf7fea-10ae-4cbf-ae97-4441cca1d938', max_length=255),
        ),
    ]
